# Libraries in  Python

## Introduction to Libraries in Machine Learning
What are Libraries?

In [5]:
!pip install numpy

In [6]:
import numpy as np

### **2. Creating Arrays**

Arrays are the central data structure in NumPy. You can create 1D, 2D, or even 3D arrays to store data.

In [14]:

# Creating a 1D array
arr_1d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4.,8]])
print( arr_1d)
arr_1d.shape

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 8.]]


(2, 5)

In [15]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)

In [16]:
#element wise operation
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
sum_arr = arr1 + arr2
mul_arr = arr1 * arr2
print("Addition:\n", sum_arr)
print("Multiplication:\n", mul_arr)

Addition:
 [11 22 33]
Multiplication:
 [10 40 90]


In [19]:
#matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
result

array([[19, 22],
       [43, 50]])

In [25]:
#reshaping
arr = np.array([[1, 2, 3, 4, 5, 6]])
print(arr,arr.shape)
reshaped_arr = arr.reshape((2, 3))
reshaped_arr

[[1 2 3 4 5 6]] (1, 6)


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Random number generation
random_values = np.random.rand(3, 3)
print("Random Values:\n", random_values)

Random Values:
 [[0.52327612 0.49768497 0.25643218]
 [0.45142369 0.44864168 0.76311869]
 [0.48461287 0.26860659 0.36621342]]
